package jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.jasper.runtime.*;

public class MainMenu_jsp extends HttpJspBase {


  private static java.util.Vector _jspx_includes;

  public java.util.List getIncludes() {
    return _jspx_includes;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    javax.servlet.jsp.PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n  <head>\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n        <!-- lib css-->\r\n    <link rel=\"stylesheet\" href=\"js/lib/text_layer_builder.css\">\r\n    <title>Ez Translate</title>\r\n    <script src=\"/ksf/js/hypas-api.js\" language=\"JavaScript\"></script>\r\n    <script src=\"js/script.js\"></script>\r\n        <!-- More Scripts at the bottom of the page-->\r\n\t\t<!-- Library PDF.JS -->\r\n    <script src=\"js/lib/pdf.js\"></script>\r\n    <script src=\"js/lib/pdf.worker.js\"></script>\r\n    <script src=\"js/lib/text_layer_builder.js\"></script>\r\n\t\t<!-- Library PDF.JS -->\r\n\r\n  </head>\r\n\r\n  <body onload=\"HyPAS.App.fullScreen(false);\">\r\n    <div id=\"mainBody\">\r\n\r\n        <div class=\"header\">\r\n            <button type=\"button\">\r\n                <img src=\"img/home.png\" alt=\"Go Home\">\r\n            </button>\r\n            <h1>Ez Translate</h1>\r\n        </div>\r\n");
      out.write("\r\n        <div class=\"section\" id=\"mainUI\">\r\n            <form>\r\n                <div class=\"header\">\r\n                    <h2>Select a File</h2>\r\n                </div>\r\n                <div class=\"main\">\r\n                    <button type=\"button\">\r\n                        <img src=\"img/USB.png\" alt=\"USB\" onclick=\"openFileExplorer('/')\" >\r\n                        <p>USB\r\n                    </button>\r\n                    <!-- \r\n                    <button type=\"button\" onclick=\"pickCloudService()\">\r\n                        <img src=\"img/CloudDown.png\" alt=\"Cloud\">\r\n                        <p>Cloud\r\n                    </button>\r\n                    <button type=\"button\">\r\n                        <img src=\"img/Scan.png\" alt=\"Scan\">\r\n                        <p>Scan\r\n                    </button>\r\n                    -->\r\n\t\t\t\t\t<button type=\"button\" onclick=\"translateDocument()\">\r\n                        <img src=\"img/translate.png\" alt=\"Translate\">\r\n                        <p>Translate\r\n                    </button>\r\n");
      out.write("                </div>\r\n            </form>\r\n\r\n            <form>\r\n                <div class=\"header\">\r\n                    <h2>Select Languages</h2>\r\n                </div>\r\n                <div class=\"main\">\r\n                    <p>From:</p>\r\n                    <button type=\"button\" class=\"longButton\" onclick=\"showLanguageOptions('srcLang')\">\r\n                       <span id=\"srcLang\">English</span>\r\n                    </button>\r\n\r\n                    <img src=\"img/arrow.png\" alt=\"arrow\">\r\n\r\n                    <p>To:</p>\r\n                    <button type=\"button\" class=\"longButton\" onclick=\"showLanguageOptions('tarLang')\">\r\n                       <span id=\"tarLang\">Spanish</span>\r\n                    </button>\r\n                </div>\r\n            </form>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<!--\r\n            <iframe id=\"frame\" src=\"js/lib/pdfjs/web/viewer.jsp?file=%2FTranslatorApp/tempPDFs/temp.pdf\">\r\n               Something went wrong... \r\n            </iframe>\r\n            <div id=\"edited\">\r\n            \tHello\r\n            </div>\r\n");
      out.write("\t\t\t\t\t\t-->\r\n\t\t\t\t\t<div id=\"canvasContainer\">\r\n\t\t\t\t\t</div>\r\n            <form>\r\n                <div class=\"header\">\r\n                    <h2>Save To</h2>\r\n                </div>\r\n                <div class=\"main\">\r\n                <!--\r\n                \t<a href=\"editDocument.jsp\">\r\n                \t \tTest\r\n                    </a>\r\n                    -->\r\n\t\t\t\t\t\r\n                    <button type=\"button\" onclick=\"saveToUSB()\">\r\n                        <img src=\"img/USB.png\" alt=\"USB\">\r\n                        <p>USB\r\n                    </button>\r\n                    <!--  \r\n                    <button type=\"button\" onclick=\"pickCloudService()\">\r\n                        <img src=\"img/CloudUP.png\" alt=\"Cloud\">\r\n                        <p>Cloud\r\n                    </button>\r\n                     --> \r\n                    <button type=\"button\" onclick=\"printDocument()\">\r\n                         <img src=\"img/Print.png\" alt=\"Print\">\r\n                         <p>Print\r\n                    </button>           \r\n                </div>\r\n");
      out.write("            </form>\r\n\r\n            <form>\r\n                <div class=\"header\">\r\n                    <h2>Settings</h2>\r\n                </div>\r\n                <div class=\"main\">\r\n                \t<!--\r\n                    <button type=\"button\" class=\"longButton\">\r\n                       Lock Settings \r\n                    </button>\r\n                    -->\r\n                    <p>Accent Color:</p>\r\n                    <button type=\"button\" class=\"longButton\" onclick=\"pickAColour()\">\r\n                    \tChange color\r\n                    </button>\r\n                    <!--\r\n                    <button type=\"button\" class=\"longButton\" onclick=\"\">\r\n                       Set settings as default \r\n                    </button>           \r\n                    -->\r\n                </div>\r\n            </form>\r\n        </div>\r\n<!--              Overlay               -->\r\n        <div id=\"overlay\">\r\n            <form id=\"pickCloud\">\r\n                <div class=\"header\">\r\n                    <h2>Pick a cloud service</h2>\r\n");
      out.write("                    <button type=\"button\" class=\"close\" onclick=\"exitOverlay()\">\r\n                    </button>\r\n                </div>\r\n                <div class=\"main\">\r\n                    <button type=\"button\" onclick=\"loginToCloud()\">\r\n                        <img src=\"img/gdrive.png\" alt=\"google drive\">\r\n                        <p>Google Drive</p>\r\n                    </button>\r\n                    <button type=\"button\" onclick=\"loginToCloud()\">\r\n                        <img src=\"img/mega.png\" alt=\"mega\">\r\n                        <p>Mega</p>\r\n                    </button>\r\n                    <button type=\"button\" onclick=\"loginToCloud()\">\r\n                        <img src=\"img/onedrive.png\" alt=\"one drive\">\r\n                        <p>One Drive</p>\r\n                    </button>\r\n                </div>\r\n            </form>\r\n\r\n            <form id=\"login\">\r\n                <div class=\"header\">\r\n                    <h2>Login</h2>\r\n                    <button type=\"button\" class=\"close\" onclick=\"exitOverlay()\">\r\n");
      out.write("                    </button>\r\n                </div>\r\n                <div class=\"main\">\r\n                    <input type=\"text\">\r\n                        Username\r\n                    <input type=\"text\">\r\n                        Passwords\r\n                </div>\r\n            </form>\r\n            <form id=\"pickAColour\">\r\n                <div class=\"header\">\r\n                    <h2>Pick a colour</h2>\r\n                    <button type=\"button\" class=\"close\" onclick=\"exitOverlay()\">\r\n                    </button>\r\n                </div>\r\n                <div class=\"main\">\r\n                    <button type=\"button\" onclick=\"changeColor('blue')\">\r\n                   \t\t<div class=\"colorblock\" style=\"background-color:blue\"></div>\r\n                    </button>          \r\n                    <button type=\"button\" onclick=\"changeColor('rgb(223,55,55)')\">\r\n                   \t\t<div class=\"colorblock\" style=\"background-color:rgb(233,55,55)\"></div>\r\n                    </button>          \r\n                    <button type=\"button\" onclick=\"changeColor('green')\">\r\n");
      out.write("                   \t\t<div class=\"colorblock\" style=\"background-color:green\"></div>\r\n                    </button>          \r\n                    <button type=\"button\" onclick=\"changeColor('purple')\">\r\n                   \t\t<div class=\"colorblock\" style=\"background-color:purple\"></div>\r\n                    </button>          \r\n\t\t\t\t</div> \r\n            </form>\r\n            \r\n\t\t\t<form id=\"fileExplorer\">\r\n\r\n\t\t\t</form>\r\n\t\t\t\r\n\t\t\t<form id=\"languageOptions\">\r\n                <div class=\"header\">\r\n                    <h2>Choose language</h2>\r\n                    <button type=\"button\" class=\"close\" onclick=\"exitOverlay()\">\r\n                    </button>\r\n                </div>\r\n                <div id=\"languageOptionsMain\" class=\"main\">\r\n                \t<button type=\"button\" name=\"English\" id=\"en\" class=\"longButton\" onclick=\"showSelectedLanguage('en')\">\r\n                   \t\tEnglish\r\n                    </button>\r\n                    <button type=\"button\" name=Spanish id=\"es\" class=\"longButton\" onclick=\"showSelectedLanguage('es')\">\r\n");
      out.write("                   \t\tSpanish\r\n                    </button>\r\n                    <button type=\"button\" name=\"German\" id=\"de\" class=\"longButton\" onclick=\"showSelectedLanguage('de')\">\r\n                   \t\tGerman\r\n                    </button>\r\n                    <button type=\"button\" name=\"French\" id=\"fr\" class=\"longButton\" onclick=\"showSelectedLanguage('fr')\">\r\n                   \t\tFrench\r\n                    </button>\r\n                    <button type=\"button\" name=\"Japanese\" id=\"ja\" class=\"longButton\" onclick=\"showSelectedLanguage('ja')\">\r\n                   \t\tJapanese\r\n                    </button>\r\n                    <button type=\"button\" name=\"Hindi\" id=\"hi\" class=\"longButton\" onclick=\"showSelectedLanguage('hi')\">\r\n                   \t\tHindi\r\n                    </button>\r\n                     <button type=\"button\" name=\"Italian\" id=\"it\" class=\"longButton\" onclick=\"showSelectedLanguage('it')\">\r\n                   \t\tItalian\r\n                    </button>\r\n                    <button type=\"button\" name=\"Hungarian\" id=\"hu\" class=\"longButton\" onclick=\"showSelectedLanguage('hu')\">\r\n");
      out.write("                   \t\tHungarian\r\n                    </button>\r\n\t\t\t\t</div> \r\n            </form>\r\n            \r\n            <div id=\"loadingOverlay\">\r\n            </div>\r\n\t\t\t\r\n        </div>\r\n    </div>\r\n<!--- viewer scripts\r\n\tI have done them in the same file as the jsp to \r\n\tavoid havin to deal with the importing and all that jazz -->\r\n\r\n\t<script>\r\n        //onPdfSelection\r\n\t\tfunction selectFile(path){\r\n            cleanContainer();\r\n\t\t\tconsole.log(\"Loading...\");\r\n\t\t\turl = menuUrl + \"?Action=SelectedFile&Path=\" + path;\r\n\t\t\t/*document.getElementById(\"overlay\").classList.add(\"show\");\r\n\t\t    document.getElementById(\"loadingOverlay\").classList.add(\"show\");*/\r\n\t\t\tfetch(url)\r\n\t\t\t.then((resp) =>{\r\n\t\t\t\tresp.text().then((buf) => {\r\n\t\t\t\t\t//resp.text() is a Base64 encoded pdf\r\n\t\t\t\t\tconsole.log(\"Buffer Received\");\r\n\t\t\t\t\texitOverlay();\r\n\t\t\t\t\t//convert text to base64 encoded data\r\n\t\t\t\t\tarrayData = base64toUint8Array(buf);\r\n\t\t\t\t\tconsole.log(\"Base64 -> Uint8Array: Success!\");\r\n                    //loadPDF({data: arrayData});\t\r\n");
      out.write("                    startViewer({data: arrayData});\r\n\t\t\t\t})\r\n\t\t\t});\r\n\t\t}\r\n\r\n        //------PDF VIEWER FUNCTIONALITY STARTS HERE----//\r\n        //This code block contains tall the functionality of the viewer\r\n        //Viewport will first be set to 1 so ensure the quality of the pdf\r\n        //is good then ill extract the text with its position and scale.\r\n        function startViewer(dataArray){\r\n            pdfjsLib.getDocument(arrayData)\r\n            .then((pdf) =>{\r\n                var container = document.getElementById(\"canvasContainer\");\r\n                for (var i=1; i <= pdf.numPages; i++){\r\n                    pdf.getPage(i).then((page) => {\r\n                        var scale = 1; //0.5\r\n                        var viewport = page.getViewport(scale);\r\n                        var div = document.createElement(\"div\");\r\n                        div.setAttribute(\"id\",\"page-\" + (page.pageIndex + 1));\r\n                        div.setAttribute(\"class\", \"page\");\r\n                        div.setAttribute(\"style\", \"position:relative\");\r\n");
      out.write("                        container.appendChild(div);\r\n\r\n                        var canvas = document.createElement(\"canvas\");\r\n                        div.appendChild(canvas);\r\n                        var context = canvas.getContext(\"2d\");\r\n                        canvas.height = viewport.height;\r\n                        canvas.width = viewport.width;\r\n\r\n                        var renderContext = {\r\n                            canvasContext: context,\r\n                            viewport: viewport\r\n                        };\r\n\r\n                        page.render(renderContext)\r\n                            .then(() => {\r\n                                return page.getTextContent();\r\n                            })\r\n                            .then((textCont) =>{\r\n                                var textLayerDiv = document.createElement(\"div\");\r\n                                textLayerDiv.setAttribute(\"class\", \"textLayer\");\r\n                                div.appendChild(textLayerDiv);\r\n\r\n                                var textLayer = new TextLayerBuilder({\r\n");
      out.write("                                    textLayerDiv: textLayerDiv,\r\n                                    pageIndex: page.pageIndex,\r\n                                    viewport:viewport\r\n                                });\r\n\r\n                                textLayer.setTextContent(textCont);\r\n                                textLayer.render();\r\n                                //RENDER IS DONE\r\n                                //Translation here\r\n                            })\r\n                    })\r\n                }\r\n        })\r\n        }\r\n\r\n        function cleanContainer(){\r\n            var container = document.getElementById(\"canvasContainer\");\r\n            container.innerHTML = \"\";\r\n        }\r\n\r\n        //---------------------Utility functions------------------//\r\n\t\t// base64 --> uint8Array\r\n\t\t// we will have to invert this conversion to send the pdf back\r\n\t\t// maybe move this function to a utility javascript file?\r\n\t\tfunction base64toUint8Array(data){\r\n\t\t\t// Remove \"safe for web\" characters\r\n\t\t\tdata = data.replace(/-/g,\"+\");\r\n");
      out.write("\t\t\tdata = data.replace(/_/g,\"/\");\r\n\r\n\t\t\t//Base64 --> string\r\n\t\t\tvar BASE64_MARKER = ';base64,';\r\n\t\t \tvar base64Index = data.indexOf(BASE64_MARKER) + BASE64_MARKER.length;\r\n\t\t  \tvar base64 = data.substring(base64Index);\r\n\t\t  \tvar raw = window.atob(base64);\r\n\t\t  \t//raw pdf data.\r\n\t\t  \tvar rawLength = raw.length;\r\n\t\t  \t//String --> Uint8Array\r\n\t\t  \tvar array = new Uint8Array(new ArrayBuffer(rawLength));\r\n\t\t  \tconsole.log(\"Raw Buffer length:\" + raw.length);\r\n\r\n\t\t  \tfor(var i = 0; i < rawLength; i++) {\r\n\t\t\t\tarray[i] = raw.charCodeAt(i);\r\n\t\t\t\t  //console.out(raw.charCodeAt(i));\r\n\t\t  \t}\r\n\t\t  \treturn array;\r\n\t\t}\r\n        \r\n    </script> \r\n    <script src=\"js/translate.js\"></script>\r\n</body>\r\n</html>\r\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (Throwable t) {
      out = _jspx_out;
      if (out != null && out.getBufferSize() != 0)
        out.clearBuffer();
      if (pageContext != null) pageContext.handlePageException(t);
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(pageContext);
    }
  }
}
